### ISSUE TITLE
SecurityConfig class has deprecated methods being used.

### ISSUE THREAD

**Issue by Neelesh-Janga** [ali-bouali/oauth2-social-login#1]
I appreciate your work on simplifying the code but I am facing issue with deprecated methods. It would be helpful if your can rewrite it and push it again.

 ```
 public class SecurityConfig {
  @Bean
  public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
    http
        .csrf()
        .disable()
        .authorizeHttpRequests()
        .anyRequest()
        .authenticated()
        .and()
        .oauth2Login()
    ;
    return http.build();
  }
}
```

**Comment by hendisantika** [comment]
I have no issue with that

**Comment by mammadyahyayev** [comment]
@hendisantika I think they are deprecated in Spring Security 6

**Comment by Neelesh-Janga** [comment]
> @hendisantika I think they are deprecated in Spring Security 6

Yes, it was.

**Comment by hendisantika** [comment]
Yes, it was.

Any one can send me PR for that?

**Comment by Neelesh-Janga** [comment]
> Yes, it was.
> 
> Any one can send me PR for that?

Sure, I'll do. Only security config file, right?

**Comment by Neelesh-Janga** [comment]
@hendisantika done creating a PR, please have a look and let me know your comments, if any.
Here is the link: https://github.com/ali-bouali/oauth2-social-login/pull/2

**Comment by Neelesh-Janga** [comment]
Hence zero conflicts & and latest code has been under review, I am closing this issue.

**Comment by Neelesh-Janga** [comment]
Hence zero conflicts & and latest code has been under review, I am closing this issue.
